### ISSUE TITLE
Getting started: Uploading design: Permission denied (Linux)

### ISSUE THREAD

**Issue by philtomson** [mystorm-org/BlackIce-II#11]
I followed the following steps for uploading the design from the Getting Started doc:

> Uploading your design (Mac/Linux)
> For Linux:
> 
> In first monitor terminal:
> 
> sudo bash
> stty -F /dev/ttyACM0 raw
> cat /dev/ttyACM0
> 
> Then in another programming terminal:
> 
> sudo cat chip.bin >/dev/ttyACM0

However, when I do that last step I see:

> $ sudo cat chip.bin >/dev/ttyACM0
> bash: /dev/ttyACM0: Permission denied

Checking the permissions:
> $ sudo ls -lart /dev/ttyACM0  
> crw-rw---- 1 root dialout 166, 0 Mar  1 21:07 /dev/ttyACM0

I'm running on Ubuntu Linux 17.10 if that makes any difference.

**Comment by folknology** [comment]
Sorry for the delay Phil the [documentation](https://github.com/mystorm-org/BlackIce-II/wiki/Getting-Started) has been updated, the relevant part is:
```
sudo bash
usermod -a -G tty yourUserName
usermod -a -G dialout yourUserName
stty -F /dev/ttyACM0 raw
cat /dev/ttyACM0
```
