### ISSUE TITLE
OSX stty command is wrong

### ISSUE THREAD

**Issue by wallclimber21** [mystorm-org/BlackIce-II#2]
The Getting Started Guide says:

```
sudo bash
stty -F /dev/cu.usbmodem1421 raw
cat /dev/cu.usbmodem1421
```

However, on OS X, -F does not exist. I think it should be -f instead.

See https://github.com/wallclimber21/BlackIce-II.wiki-mine/commit/ca714687aacaa14c097d8d53784286ad5cfc9203

**Comment by tomverbeure** [comment]
This has been fixed.
